server {
    listen 80;
    absolute_redirect off;

    location /report/ {
        proxy_pass http://bot:3000/;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location / {
        proxy_pass http://js:3000/;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /dev/ {
        default_type 'text/html';
        proxy_pass http://js:3000/;
        rewrite ^/dev/(.*)$ /$1 break;
        content_by_lua_block {
            local url = ngx.var.uri;
            local method = ngx.req.get_method();
            local body = nil;
            if method == 'POST' then
                ngx.req.read_body();
                body = ngx.req.get_body_data();
            end
            if method == 'POST' then
                method = ngx.HTTP_POST;
            else
                method = ngx.HTTP_GET;
            end
            local res = ngx.location.capture(url, { method = method, body = body });
            local template = io.open('/var/www/html/index.lua'):read('*a');
            template = template:gsub('{{response}}', res.body);
            local f = loadstring(template);
            f()
        }
    }
}
